datasource:
  master:
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  slave1:
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  slave2:
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


